name: DarkAges
main: com.dumptruckman.minecraft.darkages.DarkAgesPlugin
version: maven-version-number
depend: [Vault,WorldGuard]
softdepend: [Towny,Citizens]

commands:
  darkages:
    description: Main item menu.
    permission: darkages.adminmenu
  skills:
    description: Shows all of your known skills.
  spells:
    description: Shows all of your known spells.
  arena:
    description: Manages arenas
    permission: darkages.arena
    usage: /arena set <arena> <location>

permissions:
  darkages.abilities.*:
    default: op
    children:
      darkages.abilities.skills.*: true
      darkages.abilities.spells.*: true

  darkages.abilities.skills.*:
    default: op

  darkages.abilities.spells.*:
    default: op
    children:
      darkages.abilities.spells.soulstone: true

  darkages.abilities.spells.soulstone:
    default: true